----------USUARIO ADMIN (igcaceresc)----------

----------------Caso N°1 Estrategia de seguridad----------------
--Creacion de usuarios--
--Usuario PRY2205_EFT--
CREATE USER PRY2205_EFT 
IDENTIFIED BY "OracleCloud1234"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

--Usuario PRY2205_EFT_DES--
CREATE USER PRY2205_EFT_DES 
IDENTIFIED BY "OracleCloud1234"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

--Usuario PRY2205_EFT_CON--
CREATE USER PRY2205_EFT_CON 
IDENTIFIED BY "OracleCloud1234"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

--Privilegios para el usuario EFT (dueño)--

--Privilegios específicos--
GRANT CONNECT, RESOURCE TO PRY2205_EFT;
GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;
GRANT DROP PUBLIC SYNONYM TO PRY2205_EFT;
GRANT CREATE PROCEDURE TO PRY2205_EFT;
GRANT CREATE TRIGGER TO PRY2205_EFT;

--Privilegios para el usuario EFT_DES--

GRANT CONNECT TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_DES;

-- Privilegios para crear objetos propios
GRANT CREATE VIEW TO PRY2205_EFT_DES;
GRANT CREATE PROFILE TO PRY2205_EFT_DES;
GRANT CREATE USER TO PRY2205_EFT_DES;
GRANT ALTER USER TO PRY2205_EFT_DES;


--Privilegios para el usuario EFT_CON
-- Privilegios básicos
GRANT CONNECT TO PRY2205_EFT_CON;
GRANT CREATE SESSION TO PRY2205_EFT_CON;


--------------CREACIÓN DE ROLES--------------

--Para Desarrollador--
CREATE ROLE PRY2205_ROL_D;

--Para Consultor--
CREATE ROLE PRY2205_ROL_C;

COMMIT;

--Asignacion de rol a desarrollador--
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;


--Asignacion de rol a consultor--
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

COMMIT;


-------------------Usuario Dueño PRY2205_EFT-------------------
-------------------Caso N°2:Poblamiento de datos-------------------
--Poblado de tablas--

--Creacion de sinónimos públicos--

CREATE PUBLIC SYNONYM PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE PUBLIC SYNONYM PROFESION FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM COMUNA FOR PRY2205_EFT.COMUNA;
CREATE PUBLIC SYNONYM SECTOR FOR PRY2205_EFT.SECTOR;
CREATE PUBLIC SYNONYM AFP FOR PRY2205_EFT.AFP;
CREATE PUBLIC SYNONYM ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM CARTOLA_PROFESIONALES FOR PRY2205_EFT.CARTOLA_PROFESIONALES;
CREATE PUBLIC SYNONYM AUDITOR FOR PRY2205_EFT.AUDITOR;
CREATE PUBLIC SYNONYM CONTADOR FOR PRY2205_EFT.CONTADOR;
CREATE PUBLIC SYNONYM INFORMATICO FOR PRY2205_EFT.INFORMATICO;
CREATE PUBLIC SYNONYM PREVENCIONISTA FOR PRY2205_EFT.PREVENCIONISTA;
CREATE PUBLIC SYNONYM OTROS_PROFESIONALES FOR PRY2205_EFT.OTROS_PROFESIONALES;
CREATE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

--Creacion de sinónimos privados--
CREATE SYNONYM PROF FOR PRY2205_EFT.PROFESIONAL;
CREATE SYNONYM EMP FOR PRY2205_EFT.EMPRESA;
CREATE SYNONYM ASES FOR PRY2205_EFT.ASESORIA;
CREATE SYNONYM COM FOR PRY2205_EFT.COMUNA;
CREATE SYNONYM SECT FOR PRY2205_EFT.SECTOR;

-----------Asignacion de privilegios al rol de desarrollador-----------

--Privilegios SELECT--
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.EMPRESA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ASESORIA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.COMUNA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.SECTOR TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.AFP TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.AUDITOR TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.CONTADOR TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.INFORMATICO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PREVENCIONISTA TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.OTROS_PROFESIONALES TO PRY2205_ROL_D;

--Privilegio para otorgar privilegios a otros usuarios--
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_EFT_DES WITH GRANT OPTION;




--Privilegio sobre la secuencia--
GRANT SELECT ON PRY2205_EFT.PROFESIONAL_SEQ TO PRY2205_ROL_D;

-----------Asignacion de privilegios al rol de consultor-----------
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.EMPRESA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.ASESORIA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.COMUNA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.SECTOR TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.AFP TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;

--Privilegio sobre la secuencia--
GRANT SELECT ON PRY2205_EFT.PROFESIONAL_SEQ TO PRY2205_ROL_C;

COMMIT;

-------------Caso N°2 Permisos al usuario desarrollador-------------

GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.EMPRESA TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.ASESORIA TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.COMUNA TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.SECTOR TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.AFP TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_EFT_DES;

--Privilegios INSERT, UPDATE, DELETE sobre CARTOLA_PROFESIONALES--
GRANT INSERT, UPDATE, DELETE ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_EFT_DES;

--Privilegio sobre la secuencia--
GRANT SELECT ON PRY2205_EFT.PROFESIONAL_SEQ TO PRY2205_EFT_DES;

COMMIT;

-------------Caso N°3 Optimización de sentencias SQL-------------

-- Crear la vista editable
DROP VIEW VW_EMPRESAS_ASESORADAS
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    TRIM(TO_CHAR(e.RUT_EMPRESA, '99,999,999')) || '-' || e.DV_EMPRESA AS RUT_EMPRESA,
    UPPER(e.NOMEMPRESA) AS NOMBRE_EMPRESA,
    e.IVA_DECLARADO AS IVA,
    TRUNC(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES) / 12) AS ANIOS_EXISTENCIA,
    ROUND(COUNT(a.INICIO) / 12) AS TOTAL_ASESORIAS_ANUALES,
    ROUND((e.IVA_DECLARADO * (COUNT(a.INICIO) / 12)) / 100) AS DEVOLUCION_IVA,
    CASE 
        WHEN ROUND(COUNT(a.INICIO) / 12) > 5 THEN 'CLIENTE PREMIUM'
        WHEN ROUND(COUNT(a.INICIO) / 12) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS TIPO_CLIENTE,
    CASE 
        WHEN ROUND(COUNT(a.INICIO) / 12) > 5 THEN
            CASE 
                WHEN ROUND(COUNT(a.INICIO) / 12) >= 7 THEN '1 ASESORÍA GRATIS'
                ELSE '1 ASESORÍA 40% DE DESCUENTO'
            END
        WHEN ROUND(COUNT(a.INICIO) / 12) BETWEEN 3 AND 5 THEN
            CASE 
                WHEN ROUND(COUNT(a.INICIO) / 12) = 5 THEN '1 ASESORÍA 30% DE DESCUENTO'
                ELSE '1 ASESORÍA 20% DE DESCUENTO'
            END
        ELSE 'CAPTAR CLIENTE'
    END AS CORRESPONDE
FROM 
    EMPRESA e
    INNER JOIN ASESORIA a ON e.IDEMPRESA = a.IDEMPRESA
WHERE 
    EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND a.FIN IS NOT NULL
GROUP BY 
    e.RUT_EMPRESA,
    e.DV_EMPRESA,
    e.NOMEMPRESA,
    e.FECHA_INICIACION_ACTIVIDADES,
    e.IVA_DECLARADO
ORDER BY 
    UPPER(e.NOMEMPRESA) ASC;
CREATE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;
COMMIT;
CREATE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;
--Conceder permisos a usuario Consultor--

GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;
COMMIT;
--Plan de ejecución--
EXPLAIN PLAN FOR
SELECT * FROM VW_EMPRESAS_ASESORADAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
--Tabla EMPRESA y ASESORIA  con FULL ACCESS--

-- Índice 1: Combina IDEMPRESA y FIN para máxima optimización
DROP INDEX IDX_ASESORIA_IDEMPRESA_FIN;
CREATE INDEX IDX_ASESORIA_IDEMPRESA_FIN 
ON ASESORIA(IDEMPRESA, FIN);
--Recopilacion de estadisticas para nuevos índices--    
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(
        ownname => USER,
        tabname => 'EMPRESA',
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
    );
    
    DBMS_STATS.GATHER_TABLE_STATS(
        ownname => USER,
        tabname => 'ASESORIA',
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
    );
END;
/    

--Plan de ejecucion posterior a creacion de índices--
EXPLAIN PLAN FOR
SELECT * FROM VW_EMPRESAS_ASESORADAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-------------------Usuario Desarrollador PRY2205_EFT_DES-------------------
------------------Caso N°2 Creación de Informe------------------
--Inserción de datos a tabla CARTOLA_PROFESIONALES--

INSERT INTO PRY2205_EFT.CARTOLA_PROFESIONALES (
    RUT_PROFESIONAL,
    NOMBRE_PROFESIONAL,
    PROFESION,
    ISAPRE,
    SUELDO_BASE,
    PORC_COMISION_PROFESIONAL,
    VALOR_TOTAL_COMISION,
    PORCENTATE_HONORARIO,
    BONO_MOVILIZACION,
    TOTAL_PAGAR
)
SELECT 
    --RUT del profesional--
    p.RUTPROF AS RUT_PROFESIONAL,
    
    --Nombre completo 
    INITCAP(p.NOMPRO || ' ' || p.APPPRO || ' ' || p.APMPRO) AS NOMBRE_PROFESIONAL,
    
    --Profesión--
    prof.NOMPROFESION AS PROFESION,
    
    --Nombre de ISAPRE--
    NVL(i.NOMISAPRE, '') AS ISAPRE,
    
    --Sueldo Base--
    p.SUELDO AS SUELDO_BASE,
    
    -- Porcentaje de comisión-- 
    NVL(p.COMISION, 0) AS PORC_COMISION_PROFESIONAL,
    
    --Valor total de comisión--
    ROUND(NVL(p.SUELDO * p.COMISION, 0)) AS VALOR_TOTAL_COMISION,
    
    --Porcentaje de honorario según rango de sueldo--
    ROUND(p.SUELDO * (
        CASE 
            WHEN p.SUELDO BETWEEN 150000 AND 300000 THEN 0.40
            WHEN p.SUELDO BETWEEN 300001 AND 500000 THEN 0.38
            WHEN p.SUELDO BETWEEN 500001 AND 800000 THEN 0.36
            WHEN p.SUELDO BETWEEN 800001 AND 1200000 THEN 0.34
            WHEN p.SUELDO BETWEEN 1200001 AND 1500000 THEN 0.30
            WHEN p.SUELDO BETWEEN 1500001 AND 2000000 THEN 0.28
            WHEN p.SUELDO BETWEEN 2000001 AND 3000000 THEN 0.26
            WHEN p.SUELDO BETWEEN 3000001 AND 5000000 THEN 0.24
            ELSE 0
        END
    )) AS PORCENTATE_HONORARIO,
    
    --Bono de movilización según tipo de contrato--
    CASE tc.NOMTCONTRATO
        WHEN 'Indefinido Jornada Completa' THEN 150000
        WHEN 'Indefinido Jornada Parcial' THEN 120000
        WHEN 'Plazo fijo' THEN 60000
        WHEN 'Honorarios' THEN 50000
        ELSE 0
    END AS BONO_MOVILIZACION,
    
    --Total a pagar--
    ROUND(
        p.SUELDO + 
        NVL(p.SUELDO * p.COMISION, 0) +
        (p.SUELDO * (
            CASE 
                WHEN p.SUELDO BETWEEN 150000 AND 300000 THEN 0.40
                WHEN p.SUELDO BETWEEN 300001 AND 500000 THEN 0.38
                WHEN p.SUELDO BETWEEN 500001 AND 800000 THEN 0.36
                WHEN p.SUELDO BETWEEN 800001 AND 1200000 THEN 0.34
                WHEN p.SUELDO BETWEEN 1200001 AND 1500000 THEN 0.30
                WHEN p.SUELDO BETWEEN 1500001 AND 2000000 THEN 0.28
                WHEN p.SUELDO BETWEEN 2000001 AND 3000000 THEN 0.26
                WHEN p.SUELDO BETWEEN 3000001 AND 5000000 THEN 0.24
                ELSE 0
            END
        )) +
        (CASE tc.NOMTCONTRATO
            WHEN 'Indefinido Jornada Completa' THEN 150000
            WHEN 'Indefinido Jornada Parcial' THEN 120000
            WHEN 'Plazo fijo' THEN 60000
            WHEN 'Honorarios' THEN 50000
            ELSE 0
        END)
    ) AS TOTAL_PAGAR

FROM 
    PROFESIONAL p
    INNER JOIN PROFESION prof ON p.IDPROFESION = prof.IDPROFESION
    LEFT JOIN ISAPRE i ON p.IDISAPRE = i.IDISAPRE
    LEFT JOIN TIPO_CONTRATO tc ON p.IDTCONTRATO = tc.IDTCONTRATO

ORDER BY 
    prof.NOMPROFESION,     
    p.SUELDO DESC,          
    p.COMISION,          
    p.RUTPROF;              

COMMIT;

--Consulta del informe generado--
SELECT 
    RUT_PROFESIONAL,
    NOMBRE_PROFESIONAL,
    PROFESION,
    ISAPRE,
    LPAD(TO_CHAR(SUELDO_BASE), 15, ' ') AS SUELDO_BASE,
    LPAD(TO_CHAR(PORC_COMISION_PROFESIONAL, '0,99'), 15, ' ') AS PORC_COMISION,
    LPAD(TO_CHAR(VALOR_TOTAL_COMISION), 20, ' ') AS VALOR_TOTAL_COMISION,
    LPAD(TO_CHAR(PORCENTATE_HONORARIO), 21, ' ') AS PORCENTAJE_HONORARIO,
    LPAD(TO_CHAR(BONO_MOVILIZACION), 20, ' ') AS BONO_MOVILIZACION,
    LPAD(TO_CHAR(TOTAL_PAGAR), 15, ' ') AS TOTAL_PAGAR
FROM 
    PRY2205_EFT.CARTOLA_PROFESIONALES
ORDER BY 
    PROFESION,
    SUELDO_BASE DESC,
    PORC_COMISION_PROFESIONAL,
    RUT_PROFESIONAL;
    
--Permiso para usuario consultor tabla CARTOLA_PROFESIONALES--
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;

-------------------Usuario Consultor PRY2205_EFT_CON-------------------

---------------Caso N°3: Acceso de usuario Consultor a vistas y tablas---------------
--Consulta de vista con sinónimo publico--
SELECT * FROM VW_EMPRESAS_ASESORADAS;
--Consulta de tabla con sinónimo publico--
SELECT * FROM CARTOLA_PROFESIONALES;